/**
 * Copyright (c) 2026 Gabriel Guerrer
 *
 * Distributed under the MIT license - See LICENSE for details
 */

/*
The RNG module is the core of the RAVA architecture, responsible for entropy generation and its
delivery to the host device. The exact mechanisms used to generate pulse counts, bits, and bytes
depend on the underlying hardware platform and must be implemented by the application through the
functions `rng_gen_pulse_count()`, `rng_gen_bit()`, and `rng_gen_byte()`.

In addition to single-request generation, the module also supports continuous byte-stream
transmissions. In this mode, the application must implement the `rng_start_byte_stream()`
functionality, typically using a hardware timer interrupt to trigger the generation of random bytes
at fixed intervals.

The general functionalities provided by this module include:

- Configuration of the RNG device, consisting of the PWM boost frequency and duty cycle parameters,
and the sampling interval used to count rising-edge pulses generated by the comparators monitoring
the avalanche noise sources

- Optional post-processing of generated random bytes using XOR-based methods

- Generation and transmission of pulse counts, random bits, random bytes, uniformly distributed
integers and floating-point values.

Implementation-specific functionality must provide the hooks declared in the "Implemented by the
application" section.
*/

#ifndef RAVA_RNG_H
#define RAVA_RNG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stdint.h>
#include "rava_comm.h"
#include "rava_comm_handlers.h"
#include "rava_pwm_boost.h"
#include "rava_tools.h"

/* ===========================
 * RAVA RNG
 * =========================== */

/*
Maximum number of random bytes accepted per generation request. This value affects the maximum
time the device may remain busy processing a single request before handling other commands or
interrupts.
*/
#ifndef RNG_GEN_MAX_NBYTES_PER_CORE
#define RNG_GEN_MAX_NBYTES_PER_CORE 1024
#endif

// Runtime configuration of the RNG device
typedef struct rng_config_t
{
  pwm_boost_config_t pwm_boost;
  uint8_t sampling_interval;
} rng_config_t;

// Configuration and runtime state for fixed-interval random-byte streaming
typedef struct rng_byte_stream_t
{
  uint8_t cli_id, req_id;
  comm_interface_t *comm_if;
  uint16_t n_bytes_per_core, interval_ms, interval_ms_max;
  uint8_t postproc_id, rng_cores;
  volatile bool streaming;
  volatile bool triggered; // Used in (ISR) TIMER3_COMPA_vect
}
rng_byte_stream_t;

extern rng_config_t rng_cfg;
extern rng_byte_stream_t rng_byte_stream_cfg;

/*
RNG output modes based on the entropy sources A and B.

AB_DUAL : Returns two separate output streams for cores A and B
AB_ALT  : Returns a single stream with alternating bytes from A and B
AB_XOR  : Returns a single stream formed by XORing corresponding bytes from A and B
A       : Returns a single stream generated by core A
B       : Returns a single stream generated by core A
*/
enum RNG_CORES
{
  RNG_CORES_AB_DUAL,
  RNG_CORES_AB_ALT,
  RNG_CORES_AB_XOR,
  RNG_CORES_A,
  RNG_CORES_B,
  RNG_CORES_ENUM_LAST
};

/*
Available byte post-processing modes.

NONE       : No post-processing. Raw RNG bytes are returned unchanged
XOR        : Generates two consecutive bytes and returns their bitwise XOR
XOR DICHTL : Generates two consecutive bytes and combines them using the Dichtl method

Reference:
M. Dichtl, "Bad and Good Ways of Post-processing Biased Physical Random Numbers",
Fast Software Encryption (FSE 2007), Springer, 2007.
*/
enum RNG_BYTE_POST_PROCESSING
{
  RNG_PP_NONE,
  RNG_PP_XOR,
  RNG_PP_XOR_DICHTL,
  RNG_PP_ENUM_LAST
};

bool rng_setup(uint8_t sampling_interval);
uint8_t rng_get_sampling_interval(void);

void rng_write_pulse_counts(comm_interface_t *const comm_if, uint16_t n_counts_per_core, uint8_t rng_cores);
void rng_write_bit(comm_interface_t *const comm_if, uint8_t rng_cores);
void rng_write_bytes(comm_interface_t *const comm_if, uint16_t n_bytes_per_core, uint8_t rng_cores, uint8_t postproc_id);
void rng_write_byte_stream(void);

void rng_write_int8s(comm_interface_t *const comm_if, uint16_t n_ints, uint8_t int_delta, uint8_t postproc_id);
void rng_write_int16s(comm_interface_t *const comm_if, uint16_t n_ints, uint16_t int_delta, uint8_t postproc_id);
void rng_write_floats(comm_interface_t *const comm_if, uint16_t n_floats, uint8_t postproc_id);
void rng_write_floats_downey(comm_interface_t *const comm_if, uint16_t n_floats, uint8_t postproc_id);

// COMM
void comm_rng_get_config(comm_interface_t *const comm_if);
void comm_rng_set_config(comm_interface_t *const comm_if);
void comm_rng_set_timing_debug(comm_interface_t *const comm_if);
void comm_rng_gen_pulse_counts(comm_interface_t *const comm_if);
void comm_rng_gen_bit(comm_interface_t *const comm_if);
void comm_rng_gen_bytes(comm_interface_t *const comm_if);
void comm_rng_gen_int8s(comm_interface_t *const comm_if);
void comm_rng_gen_int16s(comm_interface_t *const comm_if);
void comm_rng_gen_floats(comm_interface_t *const comm_if);
void comm_rng_gen_floats_downey(comm_interface_t *const comm_if);
void comm_rng_start_byte_stream(comm_interface_t *const comm_if);
void comm_rng_stop_byte_stream(comm_interface_t *const comm_if);
void comm_rng_get_status_byte_stream(comm_interface_t *const comm_if);

/* ==============================
 * Implemented by the application
 * ============================== */

void rng_init(void);
bool rng_validate_setup_pars(uint8_t sampling_interval);

void rng_read_initialize(void);
void rng_read_finalize(void);

void rng_setup_timing_debug(bool on);
void rng_timing_debug_on(void);
void rng_timing_debug_off(void);

void rng_gen_pulse_count(uint8_t *const pc_a, uint8_t *const pc_b);
void rng_gen_bit(uint8_t *const bit_a, uint8_t *const bit_b);
void rng_gen_byte(uint8_t *const byte_a, uint8_t *const byte_b);

void rng_health_monitoring(const uint8_t *const byte_a, const uint8_t *const byte_b);

void rng_start_byte_stream(comm_interface_t *const comm_if, uint16_t n_bytes_per_core, uint16_t interval_ms, uint8_t rng_cores, uint8_t postproc_id);
void rng_stop_byte_stream(void);

#ifdef __cplusplus
}
#endif

#endif